In [2]:
import numpy as np

In [2]:
# creation of numpy array 
x=np.array([1,2,3,4,5])
print(x)
print(type(x))  # ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# shape and size 
print(x.size) # total no. of elements 
print(x.shape) # dimension wise elements 
print(x.ndim)  # num of dimension 

5
(5,)
1


In [6]:
x2d = np.array([[1,2,3],[4,5,6]])
print(x2d)
print(x2d.size) # total no. of elements 
print(x2d.shape) # dimension wise elements 
print(x2d.ndim)  # num of dimension 

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [7]:
x25=np.random.randint(1,100,(5,5))
print(x25)

[[51 35 70 54 87]
 [32 55 76  8 96]
 [17  6 29 99  8]
 [41 49 42 99 15]
 [21 49 43 35 92]]


In [10]:
xseq1 = np.arange(1,101, 4 )
print('1D MATRIX')
print( xseq1)
print( xseq1.size)
print('2D MATRIX')
print(xseq1.reshape(5,5))

1D MATRIX
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
25
2D MATRIX
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [14]:
xseq1 = np.linspace(1,100, 50)
print('1D MATRIX')
print( xseq1)
print( xseq1.size)
print('2D MATRIX')
print(xseq1.reshape(10,5))

1D MATRIX
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
50
2D MATRIX
[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327  43.42857143  45.44897959  47.

In [15]:
np.ones((5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

- indexing and slicing 
- boolean filter
- maths and stats
- methods

In [16]:
x25

array([[51, 35, 70, 54, 87],
       [32, 55, 76,  8, 96],
       [17,  6, 29, 99,  8],
       [41, 49, 42, 99, 15],
       [21, 49, 43, 35, 92]])

In [17]:
# first row 
print(x25[0])

[51 35 70 54 87]


In [18]:
# last row
print(x25[-1])

[21 49 43 35 92]


In [19]:
# single element 
print(x25[0,1])  # same as print(x25[0][1])

35


In [22]:
# first column
print(x25[:,0])

# 2nd columns
print(x25[:,1])

# 3rd column
print(x25[:,2])



[51 32 17 41 21]
[35 55  6 49 49]
[70 76 29 42 43]


In [24]:
# column 0, 1 index
print(x25[:,[0,1]])


[[51 35]
 [32 55]
 [17  6]
 [41 49]
 [21 49]]


In [25]:
# column 0, 1,2 index
print(x25[:,[0,1,2]])  # same as print(x25[:,:3])



[[51 35 70]
 [32 55 76]
 [17  6 29]
 [41 49 42]
 [21 49 43]]


#### Slicing in MATRIX

In [27]:
print(x25[:4,[0,1]])
print(x25[1:,3:])
print(x25[:,[0,1,2]])


[[51 35]
 [32 55]
 [17  6]
 [41 49]]
[[ 8 96]
 [99  8]
 [99 15]
 [35 92]]
[[51 35 70]
 [32 55 76]
 [17  6 29]
 [41 49 42]
 [21 49 43]]


### Boolean filter in MATRIX

In [28]:
x25

array([[51, 35, 70, 54, 87],
       [32, 55, 76,  8, 96],
       [17,  6, 29, 99,  8],
       [41, 49, 42, 99, 15],
       [21, 49, 43, 35, 92]])

In [30]:
# filter without numpy boolean filter (bad idea)
for i in x25:
    for j in i :
        if j<=20:
            print(j)

8
17
6
8
15


In [31]:
x25 <= 20 # boolean filter

array([[False, False, False, False, False],
       [False, False, False,  True, False],
       [ True,  True, False, False,  True],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [32]:
x25 [ x25 <= 20]

array([ 8, 17,  6,  8, 15])

In [35]:
x25 [ x25 >= 50] # square brackets are filter

array([51, 70, 54, 87, 55, 76, 96, 99, 99, 92])

In [38]:
(x25 > 20) & (x25 <70)

array([[ True,  True, False,  True, False],
       [ True,  True, False, False, False],
       [False, False,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True,  True, False]])

In [37]:
x25 [(x25 > 20) & (x25 <70)]

array([51, 35, 54, 32, 55, 29, 41, 49, 42, 21, 49, 43, 35])

In [39]:
np.append(x25, [1,2,3,4,5])

array([51, 35, 70, 54, 87, 32, 55, 76,  8, 96, 17,  6, 29, 99,  8, 41, 49,
       42, 99, 15, 21, 49, 43, 35, 92,  1,  2,  3,  4,  5])

In [42]:
np.append(x25, np.array([[1,2,3,4,5]]), axis= 0)

array([[51, 35, 70, 54, 87],
       [32, 55, 76,  8, 96],
       [17,  6, 29, 99,  8],
       [41, 49, 42, 99, 15],
       [21, 49, 43, 35, 92],
       [ 1,  2,  3,  4,  5]])

In [44]:
np.append(x25, np.array([[1],[2],[3],[4],[5]]), axis= 1)

array([[51, 35, 70, 54, 87,  1],
       [32, 55, 76,  8, 96,  2],
       [17,  6, 29, 99,  8,  3],
       [41, 49, 42, 99, 15,  4],
       [21, 49, 43, 35, 92,  5]])

In [48]:
# making MATRIX of 2 X 3 and 3 X 2
a=np.random.randint(1,100,(2,3))
b=np.random.randint(1,100,(3,2))

In [52]:

print(a.shape)
print(b.shape)

(2, 3)
(3, 2)


In [54]:
a

array([[44, 48, 18],
       [45, 29, 55]])

In [55]:
a.T   # a.transpose()

array([[44, 45],
       [48, 29],
       [18, 55]])

In [63]:
print(np.hstack(( a, b.T)))   # stacking of MATRIX 
print (np.hstack(( a.T, b)) )

[[44 48 18 37 20 95]
 [45 29 55 41 71  5]]
[[44 45 37 41]
 [48 29 20 71]
 [18 55 95  5]]


In [3]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x)
print()
print(y)
print("add")
print(x + y)
print("subtsract")
print(x - y)
print("divide")
print(x / y)
print("multipy")
print(x * y)
print("mod")
print(x %  y)

[[6 5 3]
 [9 3 3]
 [6 6 3]]

[[3 6 3]
 [9 3 2]
 [8 6 8]]
add
[[ 9 11  6]
 [18  6  5]
 [14 12 11]]
subtsract
[[ 3 -1  0]
 [ 0  0  1]
 [-2  0 -5]]
divide
[[2.         0.83333333 1.        ]
 [1.         1.         1.5       ]
 [0.75       1.         0.375     ]]
multipy
[[18 30  9]
 [81  9  6]
 [48 36 24]]
mod
[[0 5 0]
 [0 0 1]
 [6 0 3]]


In [4]:
print(x.dot(y))  
print()

[[87 69 52]
 [78 81 57]
 [96 72 54]]



In [5]:
x.sum()  # sum of all values 

44

In [6]:
x.sum(axis=0)  # row wise sum

array([21, 14,  9])

In [7]:
x.sum(axis=1)  # column wise sum

array([14, 15, 15])

In [8]:
print(x.mean())  # all
print(x.mean(axis = 0)) # row wise
print(x.mean(axis = 1)) # column wise

4.888888888888889
[7.         4.66666667 3.        ]
[4.66666667 5.         5.        ]


In [9]:
print(x.max()) # max value 
print(x.min())  # min value 
print(x.argmax())  # index of max value
print(x.argmin()) # index of min value 
print(x.flatten()[4]) # accessing the index value given by argmax


9


In [10]:
np.median(x )
# some function are called using np, if not available through variable 

5.0